### ISSUE TITLE
cli: test: grep parameter doing nothing

### ISSUE THREAD

**Issue by nitwhiz** [zapier/zapier-platform#338] opened 2021-03-02 07:17 UTC
I'm trying to run a specific test (ideally test suite), so I'm running `zapier test --grep magic`.

I have a test suite:

```js
describe('magic', () => { ... });
```

And in it I tried the `it` and the `test` syntax:

```js
it('should do magic stuff', () => { ... });
```

```js
test('do magic stuff', () => { ... });
```

**What I expect:** Either only the `describe` block or the `it`/`test`-blocks containing the word "magic" are executed.

**What happens:** All tests run regardless.

What am I doing wrong?

**Comment by xavdid** [comment] 2021-03-09 23:49
@nitwhiz Great question! the `--grep` flag passes that onto whatever your test handler is: https://github.com/zapier/zapier-platform/blob/123b05df790dd9a582b519ab48a05b8e44a24f19/packages/cli/src/oclif/commands/test.js#L41-L43

So this is what's ultimately run:

`npm run --silent test -- --grep=magic`

That command working will depend on your test framework. That was how it worked in `mocha`, but checking the docs, it looks like `jest` (the new `zapier init` default) works a little differently. That may be a sign we need to pull the whole thing. 

In the meantime, do you mind using `zapier validate` and `npm test --grep magic` instead? that's basically the same thing. Plus, you don't need to validate that often.

**Comment by nitwhiz** [comment] 2021-03-10 07:24
No, using `npm test --grep magic` totally works for me, no worries. I thought the `zapier test` command does some necessary prep-work, that's why I've always used it with `--skip-validate`. But I guess I just mixed up some information there.

Thanks for the intel! :)

**Comment by xavdid** [comment] 2021-03-10 16:16
Well gosh, now i'm curious why it's acting up. 

No rush, but could you let me what testing framework (and major version) you're using and I'll see if I can reproduce?

**Comment by nitwhiz** [comment] 2021-03-11 07:29
I'm using TypeScript and Jest, so for testing I have ts-jest:
```
"jest": ">=26.0.0 <27.0.0",
"ts-jest": ">=26.0.0 <27.0.0",
````

Jest being configured as follows:

```js
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: [
    './test',
    './src'
  ],
  collectCoverageFrom: [
    './src/**/*.ts'
  ],
  coverageDirectory: './coverage',
  coverageReporters: [
    'html',
    'text',
    'text-summary'
  ],
  collectCoverage: true,
  testTimeout: 10000
};
```

My `package.json` scripts section is as follows:

```
"scripts": {
    "test": "jest --no-cache",
    "build": "npm run clean && tsc",
    "clean": "rimraf ./dist ./build",
    "dev": "npm run clean && tsc --watch",
    "validate": "npm run build && zapier validate",
    "_zapier-build": "npm run build"
  },
```

Normally I run tests as `zapier test --skip-validate`.

**Comment by xavdid** [comment] 2021-03-11 17:25
Appreciate that! I'll go ahead and close this, but I'll take a look at those CLI args soon. 

Thanks for the feedback!

**Closed by xavdid** 2021-03-11 17:25 UTC
Labels: question

**Comment by xavdid** [comment] 2021-03-16 22:30
Improved in the linked PR ^

Thanks!
